# Generated by Django 3.2.16 on 2023-01-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartitems',
            new_name='Cartitem',
        ),
    ]
