# Generated by Django 3.2.16 on 2023-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230117_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='product_img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(default=-1, max_length=150),
            preserve_default=False,
        ),
    ]
