# Generated by Django 3.2.16 on 2023-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230117_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default=-1, editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
