# Generated by Django 3.2.16 on 2023-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default=None, editable=False, max_length=150),
        ),
    ]
