# Generated by Django 3.2.16 on 2023-01-25 13:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='product_title', unique=True),
        ),
    ]
