# Generated by Django 3.2.16 on 2023-01-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cartitem',
        ),
        migrations.DeleteModel(
            name='SavedItem',
        ),
    ]
