# Generated by Django 3.2.16 on 2023-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20230127_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default=-1, max_length=150),
            preserve_default=False,
        ),
    ]
