# Generated by Django 3.2.16 on 2023-03-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_product_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_product',
        ),
    ]
