# Generated by Django 3.2.16 on 2023-03-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_category_featured_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_product',
        ),
    ]
